---

language: python
python: "3.7-dev"

sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible ansible-lint

script:
  - ansible-lint .
  - cd tests && ansible-playbook -i inventory test.yml --syntax-check
